In [1]:
# -*-coding:utf-8
from sklearn.cluster import KMeans
from sklearn import preprocessing
import pandas as pd
import numpy as np
from skimage import color

# 加载数据
data = pd.read_csv("./data/football_data.csv",encoding='gbk')
train_x = data[['2019年国际排名','2018世界杯','2015亚洲杯']]
df=pd.DataFrame(train_x)
df

    2019年国际排名  2018世界杯  2015亚洲杯
0          73       40        7
1          60       15        5
2          61       19        2
3          34       18        6
4          67       26       10
5          91       40        4
6         101       40       13
7          81       40        6
8          88       40        8
9         122       40       17
10        102       50       17
11         87       50       12
12        116       50       11
13        110       50       14
14        164       50       17
15         40       30        1
16         76       40       17
17        118       50        9
18        160       50       15
19         96       50       16

K-Means

In [4]:
kmeans = KMeans(n_clusters=3)

规范化到 [0,1] 区间

In [5]:
min_max_scaler = preprocessing.MinMaxScaler()
train_x=min_max_scaler.fit_transform(train_x)

kmeans 拟合和预测

In [6]:
kmeans.fit(train_x)
predict_y=kmeans.predict(train_x)
predict_y

array([2, 1, 1, 1, 1, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
      dtype=int32)

合并聚类结果，插入到原数据中

In [7]:
result = pd.concat((data,pd.DataFrame(predict_y)),axis=1)
result.rename({0:'聚类'},axis=1,inplace=True)
result

        国家  2019年国际排名  2018世界杯  2015亚洲杯  聚类
0       中国         73       40        7   2
1       日本         60       15        5   1
2       韩国         61       19        2   1
3       伊朗         34       18        6   1
4       沙特         67       26       10   1
5      伊拉克         91       40        4   2
6      卡塔尔        101       40       13   0
7      阿联酋         81       40        6   2
8   乌兹别克斯坦         88       40        8   2
9       泰国        122       40       17   0
10      越南        102       50       17   0
11      阿曼         87       50       12   0
12      巴林        116       50       11   0
13      朝鲜        110       50       14   0
14      印尼        164       50       17   0
15      澳洲         40       30        1   1
16     叙利亚         76       40       17   0
17      约旦        118       50        9   0
18     科威特        160       50       15   0
19    巴勒斯坦         96       50       16   0

规范标准化，均值为 0，方差为 1

In [8]:
standard_scaler=preprocessing.StandardScaler()
train_x=standard_scaler.fit_transform(train_x)

kmeans 算法

In [ ]:
kmeans=KMeans(n_clusters=5)
kmeans.fit(train_x)
predict_y=kmeans.predict(train_x)

合并聚类结果，插入到原始数据中

In [10]:
result=pd.concat((data,pd.DataFrame(predict_y)),axis=1)
result.rename({0:'聚类'},axis=1,inplace=True)
result

        国家  2019年国际排名  2018世界杯  2015亚洲杯  聚类
0       中国         73       40        7   2
1       日本         60       15        5   1
2       韩国         61       19        2   1
3       伊朗         34       18        6   1
4       沙特         67       26       10   1
5      伊拉克         91       40        4   2
6      卡塔尔        101       40       13   0
7      阿联酋         81       40        6   2
8   乌兹别克斯坦         88       40        8   2
9       泰国        122       40       17   0
10      越南        102       50       17   0
11      阿曼         87       50       12   0
12      巴林        116       50       11   0
13      朝鲜        110       50       14   0
14      印尼        164       50       17   0
15      澳洲         40       30        1   1
16     叙利亚         76       40       17   0
17      约旦        118       50        9   0
18     科威特        160       50       15   0
19    巴勒斯坦         96       50       16   0

使用 K-means 对图像进行聚类，显示分割标识的可视化

In [14]:

import numpy as np
import PIL.Image as image
from sklearn.cluster import KMeans
from sklearn import preprocessing

# 加载图像，并对数据进行可视化
def load_file(file_path):
    # 读文件
    f = open(file_path,'rb')
    data = []
    # 得到图像的像素值
    img = image.open(f)
    # 得到图像尺寸
    width,height=img.size
    for x in range(width):
        for y in range(height):
            # 得到点 (x,y) 的三个通道值
            c1,c2,c3=img.getpixel((x,y))
            data.append([c1,c2,c3])
    f.close()
    # 采用 Min-Max规范化
    mm=preprocessing.MinMaxScaler()
    data = mm.fit_transform(data)
    return np.mat(data),width,height

# 加载图像，得到规范化的结果 img，以及图像尺寸
img,width,height=load_file('/Users/wangyunfei/Desktop/Data/weixin.jpg')

# 用 K-Means 对图像进行 2聚类
kmeans=KMeans(n_clusters=2)
kmeans.fit(img)
label = kmeans.predict(img)
# 将图像聚类结果，转化成图像尺寸的矩阵
label = label.reshape([width,height])
# 创建新图像 poc_mark，用来保存图像聚类的结果，并设置不同的灰度值
pic_mark = image.new("L",(width,height))
for x in range(width):
    for y in range(height):
        # 根据类别设置图像的灰度值，类别 0 灰度值 255，类别 1 灰度值 127
        pic_mark.putpixel((x,y),int(256/(label[x][y]+1))-1)
pic_mark.save("/Users/wangyunfei/Desktop/Data/weixin_mark.jpg",'JPEG')

In [16]:
# 进行 16 聚类
kmeans=KMeans(n_clusters=16)
kmeans.fit(img)
label=kmeans.predict(img)
# 将图像聚类结果，转化成图像尺寸的矩阵
label = label.reshape([width,height])
# 将聚类标识矩阵转化为不同颜色的矩阵
label_color = (color.label2rgb(label)*255).astype(np.uint8)
label_color = label_color.transpose(1,0,2)
images = image.fromarray(label_color)
images.save('/Users/wangyunfei/Desktop/Data/weixin_mark_coloer.jpg')

In [19]:
# 加载图像，并对数据进行可视化
def load_file1(file_path):
    # 读文件
    f = open(file_path,'rb')
    data = []
    # 得到图像的像素值
    img = image.open(f)
    # 得到图像尺寸
    width,height=img.size
    for x in range(width):
        for y in range(height):
            # 得到点 (x,y) 的三个通道值
            c1,c2,c3=img.getpixel((x,y))
            # 自定义规范化
            data.append([(c1+1)/256.0,(c2+1)/256.0,(c3+1)/256.0])
    f.close()
    return np.mat(data),width,height

# 加载图像，得到规范化的结果imgData，以及图像尺寸
img, width, height = load_file1('/Users/wangyunfei/Desktop/Data/weixin.jpg')
# 用K-Means对图像进行16聚类
kmeans =KMeans(n_clusters=16)
label = kmeans.fit_predict(img)
# 将图像聚类结果，转化成图像尺寸的矩阵
label = label.reshape([width, height])
# 创建个新图像img，用来保存图像聚类压缩后的结果
img=image.new('RGB', (width, height))
for x in range(width):
    for y in range(height):
        c1 = kmeans.cluster_centers_[label[x, y], 0]
        c2 = kmeans.cluster_centers_[label[x, y], 1]
        c3 = kmeans.cluster_centers_[label[x, y], 2]
        img.putpixel((x, y), (int(c1*256)-1, int(c2*256)-1, int(c3*256)-1))
img.save('/Users/wangyunfei/Desktop/Data/weixin_new.jpg')